In [20]:
import numpy as np
import pandas as pd
from pathlib import Path

In [21]:
diabetes_df = pd.read_csv(Path('diabetes-dataset.csv'))
pimaData_df = pd.read_csv(Path('diabetes_PIMA_INDIANS.csv'))
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0

In [22]:
#df_new = df.drop(df[(df['col_1'] == 1.0) & (df['col_2'] == 0.0)].index)
diabetes_df_cl = diabetes_df.drop(diabetes_df[(diabetes_df['BloodPressure']==0) | (diabetes_df['Glucose']==0)
                    | (diabetes_df['SkinThickness']==0) | (diabetes_df['Insulin']==0)
                    | (diabetes_df['Age']==0) | (diabetes_df['BMI']==0)].index)

diabetes_df_cl.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,1035.000000,1035.000000,1035.000000,1035.000000,1035.000000,1035.000000,1035.000000,1035.000000,1035.000000
mean,3.185507,122.842512,70.803865,29.263768,153.946860,33.307633,0.522839,30.670531,0.325604
std,3.167531,30.653888,12.336324,10.558989,111.489069,7.097899,0.332292,10.047212,0.468827
min,0.000000,56.000000,24.000000,7.000000,14.000000,18.200000,0.085000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,21.000000,76.500000,28.500000,0.282000,23.000000,0.000000
50%,2.000000,120.000000,70.000000,29.000000,126.000000,33.300000,0.452000,27.000000,0.000000
75%,5.000000,143.000000,78.000000,37.000000,190.000000,37.400000,0.684500,36.000000,1.000000
max,17.000000,198.000000,110.000000,63.000000,744.000000,67.100000,2.420000,81.000000,1.000000

In [23]:
pimaData_df_cl = pimaData_df.drop(pimaData_df[(pimaData_df['BloodPressure']==0) | (pimaData_df['Glucose']==0)
                    | (pimaData_df['SkinThickness']==0) | (pimaData_df['Insulin']==0)
                    | (pimaData_df['Age']==0) | (pimaData_df['BMI']==0)].index)

pimaData_df_cl.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,3.301020,122.627551,70.663265,29.145408,156.056122,33.086224,0.523046,30.864796,0.331633
std,3.211424,30.860781,12.496092,10.516424,118.841690,7.027659,0.345488,10.200777,0.471401
min,0.000000,56.000000,24.000000,7.000000,14.000000,18.200000,0.085000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,21.000000,76.750000,28.400000,0.269750,23.000000,0.000000
50%,2.000000,119.000000,70.000000,29.000000,125.500000,33.200000,0.449500,27.000000,0.000000
75%,5.000000,143.000000,78.000000,37.000000,190.000000,37.100000,0.687000,36.000000,1.000000
max,17.000000,198.000000,110.000000,63.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [24]:
pimaData_df_cl.to_csv("CleanerPimaData.csv", index=False)

In [25]:
diabetes_df_cl.to_csv("CleanerDiabetesData.csv", index=False)